/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as QrCodeImport } from './routes/qr.$code'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QrCodeRoute = QrCodeImport.update({
  id: '/qr/$code',
  path: '/qr/$code',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/qr/$code': {
      id: '/qr/$code'
      path: '/qr/$code'
      fullPath: '/qr/$code'
      preLoaderRoute: typeof QrCodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qr/$code': typeof QrCodeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qr/$code': typeof QrCodeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/qr/$code': typeof QrCodeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/qr/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/qr/$code'
  id: '__root__' | '/' | '/qr/$code'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QrCodeRoute: typeof QrCodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QrCodeRoute: QrCodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/qr/$code"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/qr/$code": {
      "filePath": "qr.$code.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
