name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build Web Assets
        run: |
          cd web
          bun install
          bun run build
          cd ..

      - name: Build Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o bundeck-linux-amd64 .

      - name: Build Linux (arm64)
        run: |
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w" -o bundeck-linux-arm64 .

      - name: Build Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-H=windowsgui -s -w" -o bundeck-windows-amd64.exe .

      - name: Build MacOS (amd64/arm64)
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.23
          dest: mac-build
          prefix: bundeck
          targets: darwin/amd64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Move MacOS apps
        run: |
          mv mac-build/bundeck-darwin-amd64 bundeck-mac-intel
          mv mac-build/bundeck-darwin-arm64 bundeck-mac-apple

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bundeck-linux-amd64
            bundeck-linux-arm64
            bundeck-windows-amd64.exe
            bundeck-mac-intel
            bundeck-mac-apple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
