name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build Web Assets
        run: |
          cd web
          bun install
          bun run build
          cd ..

      # Clean any previous artifacts
      - name: Clean
        run: make clean

      # Build Linux binaries
      - name: Build Linux (amd64)
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o bundeck-linux-amd64 .

      - name: Build Linux (arm64)
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w" -o bundeck-linux-arm64 .

      # Build Windows binaries
      - name: Build Windows (amd64)
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-H=windowsgui -s -w" -o bundeck-windows-amd64.exe .

      - name: Build Windows (arm64)
        run: GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-H=windowsgui -s -w" -o bundeck-windows-arm64.exe .

      # Build macOS app bundles
      - name: Build macOS App Bundles
        run: make build-macos

      # Create release with all built artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bundeck-linux-amd64
            bundeck-linux-arm64
            bundeck-windows-amd64.exe
            bundeck-windows-arm64.exe
            Bundeck-macOS-intel.zip
            Bundeck-macOS-apple.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
